name: Application Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    env:
        AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: 'GitHub_to_AWS_via_FederatedOIDC'
          aws-region: 'us-east-1'

      - name: npm Install
        run: npm install

      - name: NPM Build
        run: CI=false npm run build
        env:
          NODE_ENV: production
          REACT_APP_TOKEN_URL: ${{ vars.TOKEN_URL }}
          REACT_APP_ORCHESTRATION_URL: ${{ vars.ORCHESTRATION_URL }}
          REACT_APP_PERSONA_AUTH_MODE: 1
          REACT_APP_ORCHESTRATION_MODE: true
          ESLINT_NO_DEV_ERRORS: true
          GENERATE_SOURCEMAP: true
          REACT_APP_SESSION_SERVER: dh.az.soulmachines.cloud



      - name: Upload to S3 bucket
        run: aws s3 sync build/ s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
